### ISSUE TITLE
近期luci-theme-argon主题未编译成功问题

### ISSUE THREAD

**Issue by lgs2007m** [moruiris/Actions-OpenWrt#1]
大佬你好，我Fork你的项目编译的R3P固件，config、diy-part都没有修改，使用Lean源码和你的openwrt-packages软件包源码合集，2月4日编译过没有问题。2月18日再次编译，没有看到提示错误，但是编译出来的固件luci-theme-argon主题有问题。Web升级编译好的固件后，默认主题是bootstrap，而且自己切换为argon后也不是jerrykuku的那个argon主题（感觉是Lean自带那个argon主题），Openwrt“系统”菜单下没有“Argon 主题设置”选项。

我升级大佬你这边每日自动编译的固件，也是一样的，argon主题有问题。
我查看Lean源码下package/lean/下面已经没有luci-theme-argon的文件了，不知道是不是转移了还是怎样，搜索Lean源码也没看到argon相关文件。不知道是不是转移了所以没有删除干净……导致的。

我比较小白，看不太懂，自己解决不了。不知道大佬有没有空看看

**Comment by lgs2007m** [comment]
我看到Lean的argon主题移到 https://github.com/coolsnowwolf/luci 去了，这样在更新和安装feeds时候怎么删除呢。

**Comment by moruiris** [comment]
抱歉这么久才看到。已借用他人插件源码进行修改，编译lean时插件选择这两个：[luci-app-argonne-config]和[luci-theme-argonne]

**Comment by lgs2007m** [comment]
> 抱歉这么久才看到。已借用他人插件源码进行修改，编译lean时插件选择这两个：[luci-app-argonne-config]和[luci-theme-argonne]

明白了，我这就去修改我的config，谢谢大佬。
